function trackers = configTrackers()

trackers = {
            struct('name','CN','namePaper','CN'),...
            struct('name','KCF','namePaper','KCF'),...
            struct('name','Staple','namePaper','Staple'),...
            struct('name','ECO_HC','namePaper','ECO_HC'),...
            struct('name','AutoTrack','namePaper','AutoTrack')
            };
